version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  guard-owl:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SQLITE_DB_PATH=/app/data/guard_owl.db
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
    volumes:
      - ./guard_owl_mock_reports.json:/app/guard_owl_mock_reports.json
      - app_data:/app/data
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data:
  app_data: